export type {
	IRBinaryOperator,
	IRExpressionNode,
	IRTime,
	IRPosition,
	IRStock,
	IRAuxiliary,
	IRFlow,
	IRConnection,
	IRGraphicalFunctionKind,
	IRGraphicalFunction,
	IR,
	CompileResult,
	IRDiagnostic,
} from "@sysdml/contracts";
