// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.8_@azure+identity@4.13.1_@babel+plugin-syntax-jsx@7.29.7_@babel+core@7.29.7__@babel+_nbwwlky75kdec357twmn5xy3a4/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.8_@azure+identity@4.13.1_@babel+plugin-syntax-jsx@7.29.7_@babel+core@7.29.7__@babel+_nbwwlky75kdec357twmn5xy3a4/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.8_@azure+identity@4.13.1_@babel+plugin-syntax-jsx@7.29.7_@babel+core@7.29.7__@babel+_nbwwlky75kdec357twmn5xy3a4/node_modules/nuxt/dist/app/plugins/router.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.8_@azure+identity@4.13.1_@babel+plugin-syntax-jsx@7.29.7_@babel+core@7.29.7__@babel+_nbwwlky75kdec357twmn5xy3a4/node_modules/nuxt/dist/app/plugins/browser-devtools-timing.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.8_@azure+identity@4.13.1_@babel+plugin-syntax-jsx@7.29.7_@babel+core@7.29.7__@babel+_nbwwlky75kdec357twmn5xy3a4/node_modules/nuxt/dist/app/plugins/payload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.8_@azure+identity@4.13.1_@babel+plugin-syntax-jsx@7.29.7_@babel+core@7.29.7__@babel+_nbwwlky75kdec357twmn5xy3a4/node_modules/nuxt/dist/app/plugins/dev-server-logs.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.8_@azure+identity@4.13.1_@babel+plugin-syntax-jsx@7.29.7_@babel+core@7.29.7__@babel+_nbwwlky75kdec357twmn5xy3a4/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.8_@azure+identity@4.13.1_@babel+plugin-syntax-jsx@7.29.7_@babel+core@7.29.7__@babel+_nbwwlky75kdec357twmn5xy3a4/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.8_@azure+identity@4.13.1_@babel+plugin-syntax-jsx@7.29.7_@babel+core@7.29.7__@babel+_nbwwlky75kdec357twmn5xy3a4/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.8_@azure+identity@4.13.1_@babel+plugin-syntax-jsx@7.29.7_@babel+core@7.29.7__@babel+_nbwwlky75kdec357twmn5xy3a4/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxt+devtools@3.2.4_vite@7.3.6_@types+node@24.12.4_jiti@2.7.0_lightningcss@1.32.0_terser@5.4_k5q7geuytg7r7zksxeou6tggle/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxt+devtools@3.2.4_vite@7.3.6_@types+node@24.12.4_jiti@2.7.0_lightningcss@1.32.0_terser@5.4_k5q7geuytg7r7zksxeou6tggle/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.8_@azure+identity@4.13.1_@babel+plugin-syntax-jsx@7.29.7_@babel+core@7.29.7__@babel+_nbwwlky75kdec357twmn5xy3a4/node_modules/nuxt/dist/app/plugins/warn.dev.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.8_@azure+identity@4.13.1_@babel+plugin-syntax-jsx@7.29.7_@babel+core@7.29.7__@babel+_nbwwlky75kdec357twmn5xy3a4/node_modules/nuxt/dist/app/plugins/check-if-layout-used.js")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'vue-devtools-client' | 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:browser-devtools-timing' | 'nuxt:payload' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'nuxt:global-components' | 'nuxt:checkIfLayoutUsed'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
