import type { Span } from "../syntax/index.js";

export const DiagnosticCode = {
	MISSING_TIME_BLOCK: "MISSING_TIME_BLOCK",
	DUPLICATE_TIME_BLOCK: "DUPLICATE_TIME_BLOCK",
	MISSING_STOCK: "MISSING_STOCK",
	MISSING_STOCK_INIT: "MISSING_STOCK_INIT",
	DUPLICATE_IDENTIFIER: "DUPLICATE_IDENTIFIER",
	MISSING_FLOW_PROPERTY: "MISSING_FLOW_PROPERTY",
	INVALID_FLOW_ENDPOINT: "INVALID_FLOW_ENDPOINT",
	UNDEFINED_IDENTIFIER: "UNDEFINED_IDENTIFIER",
	INVALID_TIME_STEP: "INVALID_TIME_STEP",
	INVALID_TIME_RANGE: "INVALID_TIME_RANGE",
	UNKNOWN_FUNCTION: "UNKNOWN_FUNCTION",
	WRONG_ARITY: "WRONG_ARITY",
	INVALID_GF_KIND: "INVALID_GF_KIND",
	MISSING_YPTS: "MISSING_YPTS",
	MISSING_X_DEFINITION: "MISSING_X_DEFINITION",
	CONFLICTING_X_DEFINITION: "CONFLICTING_X_DEFINITION",
	XSCALE_WRONG_COUNT: "XSCALE_WRONG_COUNT",
	XPTS_YPTS_COUNT_MISMATCH: "XPTS_YPTS_COUNT_MISMATCH",
	XPTS_NOT_ASCENDING: "XPTS_NOT_ASCENDING",
	STEP_LAST_YPTS_MISMATCH: "STEP_LAST_YPTS_MISMATCH",
	DUPLICATE_GF: "DUPLICATE_GF",
	GF_NAME_CONFLICT: "GF_NAME_CONFLICT",
	GF_WRONG_ARITY: "GF_WRONG_ARITY",
	LOOKUP_TOO_FEW_YPTS: "LOOKUP_TOO_FEW_YPTS",
	LOOKUP_NON_LITERAL_YPTS: "LOOKUP_NON_LITERAL_YPTS",
	MULTI_MODEL_NOT_SUPPORTED: "MULTI_MODEL_NOT_SUPPORTED",
	IDENTIFIER_SHADOWS_BUILTIN: "IDENTIFIER_SHADOWS_BUILTIN",
} as const;

export type DiagnosticCode =
	(typeof DiagnosticCode)[keyof typeof DiagnosticCode];

export interface IRDiagnostic {
	code: DiagnosticCode;
	message: string;
	span?: Span;
}

export const SimDiagnosticCode = {
	CYCLE_IN_AUX: "CYCLE_IN_AUX",
	INIT_REQUIRES_IDENT: "INIT_REQUIRES_IDENT",
	INVALID_DELAY_ORDER: "INVALID_DELAY_ORDER",
	WARN_PULSE_INTERVAL: "WARN_PULSE_INTERVAL",
	FUNCTION_NOT_IN_V1: "FUNCTION_NOT_IN_V1",
	MATH_DOMAIN_ERROR: "MATH_DOMAIN_ERROR",
} as const;

export type SimDiagnosticCode =
	(typeof SimDiagnosticCode)[keyof typeof SimDiagnosticCode];

export interface SimDiagnostic {
	code: SimDiagnosticCode;
	message: string;
}
